### ISSUE TITLE
EU - PMR446 devices is limited to a maximum power output of 0.5 W

### ISSUE THREAD

**Issue by EA1FHS** [tolvanea/PMR446-channels-for-CHIRP#1]
In accordance with EU current regulations, the use of PMR446 devices is limited to a maximum power output of 0.5 W (500 mW), and the use of external antennas or modification of the equipment to increase its power is not allowed.
Please, indicate how to program this value in CHIRP files. Thank you.

**Comment by tolvanea** [comment]
Yep, good note, added that information to the readme. The [channel setting file](https://github.com/tolvanea/PMR446-channels-for-CHIRP/blob/main/pmr_UV-5R.csv) is a regular csv text file, and thus is editable. The last column is "Power"
